# 3.1 Data Preparation

In [30]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Download the data
# Look at the data
# Make column names and values looks uniform
# Check if all the columns read correctly
# Check if the churn variable needs any preparation

In [2]:
data = 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-03-churn-prediction/WA_Fn-UseC_-Telco-Customer-Churn.csv'

In [13]:
df = pd.read_csv(data)
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [14]:
cols = list(df.columns.str.replace(" ", "_").str.lower())
cols

['customerid',
 'gender',
 'seniorcitizen',
 'partner',
 'dependents',
 'tenure',
 'phoneservice',
 'multiplelines',
 'internetservice',
 'onlinesecurity',
 'onlinebackup',
 'deviceprotection',
 'techsupport',
 'streamingtv',
 'streamingmovies',
 'contract',
 'paperlessbilling',
 'paymentmethod',
 'monthlycharges',
 'totalcharges',
 'churn']

In [15]:
df.columns = cols
df.head()

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [28]:
df['customerid'].str.lower().str.replace(" ", "_")

0       7590-vhveg
1       5575-gnvde
2       3668-qpybk
3       7795-cfocw
4       9237-hqitu
           ...
7038    6840-resvb
7039    2234-xaduh
7040    4801-jzazl
7041    8361-ltmkd
7042    3186-ajiek
Name: customerid, Length: 7043, dtype: str

In [16]:
cols_str = list(df.dtypes[df.dtypes == 'str'].index)

In [17]:
for c in cols_str:
    df[c] = df[c].str.lower().str.replace(" ", "_")

df.head()

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
0,7590-vhveg,female,0,yes,no,1,no,no_phone_service,dsl,no,...,no,no,no,no,month-to-month,yes,electronic_check,29.85,29.85,no
1,5575-gnvde,male,0,no,no,34,yes,no,dsl,yes,...,yes,no,no,no,one_year,no,mailed_check,56.95,1889.5,no
2,3668-qpybk,male,0,no,no,2,yes,no,dsl,yes,...,no,no,no,no,month-to-month,yes,mailed_check,53.85,108.15,yes
3,7795-cfocw,male,0,no,no,45,no,no_phone_service,dsl,yes,...,yes,yes,no,no,one_year,no,bank_transfer_(automatic),42.30,1840.75,no
4,9237-hqitu,female,0,no,no,2,yes,no,fiber_optic,no,...,no,no,no,no,month-to-month,yes,electronic_check,70.70,151.65,yes

In [22]:
df['churn'].iloc[2] == 'yes'

True

In [ ]:

for v in ['yes']:
    df['churn'] = (df['churn'] == v).astype(int)

np.int64(1869)

In [31]:
df.dtypes

customerid              str
gender                  str
seniorcitizen         int64
partner                 str
dependents              str
tenure                int64
phoneservice            str
multiplelines           str
internetservice         str
onlinesecurity          str
onlinebackup            str
deviceprotection        str
techsupport             str
streamingtv             str
streamingmovies         str
contract                str
paperlessbilling        str
paymentmethod           str
monthlycharges      float64
totalcharges            str
churn                 int64
dtype: object

In [54]:
# totalcharges to numeric
tc = pd.to_numeric(df.totalcharges, errors='coerce')

In [42]:
df.dtypes

customerid              str
gender                  str
seniorcitizen         int64
partner                 str
dependents              str
tenure                int64
phoneservice            str
multiplelines           str
internetservice         str
onlinesecurity          str
onlinebackup            str
deviceprotection        str
techsupport             str
streamingtv             str
streamingmovies         str
contract                str
paperlessbilling        str
paymentmethod           str
monthlycharges      float64
totalcharges        float64
churn                 int64
dtype: object

In [58]:
df[tc.isnull()][['customerid', 'totalcharges']]

      customerid  totalcharges
488   4472-lvygi          True
753   3115-czmzd          True
936   5709-lvoeq          True
1082  4367-nuyao          True
1340  1371-dwpaz          True
3331  7644-omvmy          True
3826  3213-vvolg          True
4380  2520-sgtta          True
5218  2923-arzlg          True
6670  4075-wkniu          True
6754  2775-sefee          True

In [57]:

df.totalcharges = df.totalcharges.isnull().fillna(0)

In [61]:
df.totalcharges.isnull().sum()

np.int64(0)

In [62]:
df.head()

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
0,7590-vhveg,female,0,yes,no,1,no,no_phone_service,dsl,no,...,no,no,no,no,month-to-month,yes,electronic_check,29.85,False,0
1,5575-gnvde,male,0,no,no,34,yes,no,dsl,yes,...,yes,no,no,no,one_year,no,mailed_check,56.95,False,0
2,3668-qpybk,male,0,no,no,2,yes,no,dsl,yes,...,no,no,no,no,month-to-month,yes,mailed_check,53.85,False,1
3,7795-cfocw,male,0,no,no,45,no,no_phone_service,dsl,yes,...,yes,yes,no,no,one_year,no,bank_transfer_(automatic),42.30,False,0
4,9237-hqitu,female,0,no,no,2,yes,no,fiber_optic,no,...,no,no,no,no,month-to-month,yes,electronic_check,70.70,False,1

In [63]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,7033,7034,7035,7036,7037,7038,7039,7040,7041,7042
customerid,7590-vhveg,5575-gnvde,3668-qpybk,7795-cfocw,9237-hqitu,9305-cdskc,1452-kiovk,6713-okomc,7892-pookp,6388-tabgu,...,9767-fflem,0639-tsiqw,8456-qdavc,7750-eyxwz,2569-wgero,6840-resvb,2234-xaduh,4801-jzazl,8361-ltmkd,3186-ajiek
gender,female,male,male,male,female,female,male,female,female,male,...,male,female,male,female,female,male,female,female,male,male
seniorcitizen,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
partner,yes,no,no,no,no,no,no,no,yes,no,...,no,no,no,no,no,yes,yes,yes,yes,no
dependents,no,no,no,no,no,no,yes,no,no,yes,...,no,no,no,no,no,yes,yes,yes,no,no
tenure,1,34,2,45,2,8,22,10,28,62,...,38,67,19,12,72,24,72,11,4,66
phoneservice,no,yes,yes,no,yes,yes,yes,no,yes,yes,...,yes,yes,yes,no,yes,yes,yes,no,yes,yes
multiplelines,no_phone_service,no,no,no_phone_service,no,yes,yes,no_phone_service,yes,no,...,no,yes,no,no_phone_service,no,yes,yes,no_phone_service,yes,no
internetservice,dsl,dsl,dsl,dsl,fiber_optic,fiber_optic,fiber_optic,dsl,fiber_optic,dsl,...,fiber_optic,fiber_optic,fiber_optic,dsl,no,dsl,fiber_optic,dsl,fiber_optic,fiber_optic
onlinesecurity,no,yes,yes,yes,no,no,no,yes,no,yes,...,no,yes,no,no,no_internet_service,yes,no,yes,no,yes
onlinebackup,yes,no,yes,no,no,no,yes,no,no,yes,...,no,yes,no,yes,no_internet_service,no,yes,no,no,no
deviceprotection,no,yes,no,yes,no,yes,no,no,yes,no,...,no,yes,no,yes,no_internet_service,yes,yes,no,no,yes
techsupport,no,no,no,yes,no,no,no,no,yes,no,...,no,no,no,yes,no_internet_service,yes,no,no,no,yes
streamingtv,no,no,no,no,no,yes,yes,no,yes,no,...,no,yes,yes,yes,no_internet_service,yes,yes,no,no,yes
streamingmovies,no,no,no,no,no,yes,no,no,yes,no,...,no,no,no,yes,no_internet_service,yes,yes,no,no,yes
contract,month-to-month,one_year,month-to-month,one_year,month-to-month,month-to-month,month-to-month,month-to-month,month-to-month,one_year,...,month-to-month,month-to-month,month-to-month,one_year,two_year,one_year,one_year,month-to-month,month-to-month,two_year
paperlessbilling,yes,no,yes,no,yes,yes,yes,no,yes,no,...,yes,yes,yes,no,yes,yes,yes,yes,yes,yes
paymentmethod,electronic_check,mailed_check,mailed_check,bank_transfer_(automatic),electronic_check,electronic_check,credit_card_(automatic),mailed_check,electronic_check,bank_transfer_(automatic),...,credit_card_(automatic),credit_card_(automatic),bank_transfer_(automatic),electronic_check,bank_transfer_(automatic),mailed_check,credit_card_(automatic),electronic_check,mailed_check,bank_transfer_(automatic)
monthlycharges,29.85,56.95,53.85,42.3,70.7,99.65,89.1,29.75,104.8,56.15,...,69.5,102.95,78.7,60.65,21.15,84.8,103.2,29.6,74.4,105.65
totalcharges,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
churn,0,0,1,0,1,1,0,0,1,0,...,0,1,0,0,0,0,0,0,1,0

In [64]:
df.totalcharges.isnull().sum()

np.int64(0)