# 3.1 Data Preparation

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Download the data
# Look at the data
# Make column names and values looks uniform
# Check if all the columns read correctly
# Check if the churn variable needs any preparation

In [2]:
data = 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-03-churn-prediction/WA_Fn-UseC_-Telco-Customer-Churn.csv'

In [3]:
df = pd.read_csv(data)
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
cols = list(df.columns.str.replace(" ", "_").str.lower())
cols

['customerid',
 'gender',
 'seniorcitizen',
 'partner',
 'dependents',
 'tenure',
 'phoneservice',
 'multiplelines',
 'internetservice',
 'onlinesecurity',
 'onlinebackup',
 'deviceprotection',
 'techsupport',
 'streamingtv',
 'streamingmovies',
 'contract',
 'paperlessbilling',
 'paymentmethod',
 'monthlycharges',
 'totalcharges',
 'churn']

In [5]:
df.columns = cols
df.head()

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [6]:
df['customerid'].str.lower().str.replace(" ", "_")

0       7590-vhveg
1       5575-gnvde
2       3668-qpybk
3       7795-cfocw
4       9237-hqitu
           ...
7038    6840-resvb
7039    2234-xaduh
7040    4801-jzazl
7041    8361-ltmkd
7042    3186-ajiek
Name: customerid, Length: 7043, dtype: str

In [7]:
cols_str = list(df.dtypes[df.dtypes == 'str'].index)

In [8]:
for c in cols_str:
    df[c] = df[c].str.lower().str.replace(" ", "_")

df.head()

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
0,7590-vhveg,female,0,yes,no,1,no,no_phone_service,dsl,no,...,no,no,no,no,month-to-month,yes,electronic_check,29.85,29.85,no
1,5575-gnvde,male,0,no,no,34,yes,no,dsl,yes,...,yes,no,no,no,one_year,no,mailed_check,56.95,1889.5,no
2,3668-qpybk,male,0,no,no,2,yes,no,dsl,yes,...,no,no,no,no,month-to-month,yes,mailed_check,53.85,108.15,yes
3,7795-cfocw,male,0,no,no,45,no,no_phone_service,dsl,yes,...,yes,yes,no,no,one_year,no,bank_transfer_(automatic),42.30,1840.75,no
4,9237-hqitu,female,0,no,no,2,yes,no,fiber_optic,no,...,no,no,no,no,month-to-month,yes,electronic_check,70.70,151.65,yes

In [9]:
df['churn'].head() == 'yes'

0    False
1    False
2     True
3    False
4     True
Name: churn, dtype: bool

In [10]:
for v in ['yes']:
    df['churn'] = (df['churn'] == v).astype(int)

df['churn'].head().values

array([0, 0, 1, 0, 1])

In [11]:
df.dtypes

customerid              str
gender                  str
seniorcitizen         int64
partner                 str
dependents              str
tenure                int64
phoneservice            str
multiplelines           str
internetservice         str
onlinesecurity          str
onlinebackup            str
deviceprotection        str
techsupport             str
streamingtv             str
streamingmovies         str
contract                str
paperlessbilling        str
paymentmethod           str
monthlycharges      float64
totalcharges            str
churn                 int64
dtype: object

In [12]:
# totalcharges to numeric
# tc = pd.to_numeric(df.totalcharges, errors='coerce')

In [13]:
df['churn']

0       0
1       0
2       1
3       0
4       1
       ..
7038    0
7039    0
7040    0
7041    1
7042    0
Name: churn, Length: 7043, dtype: int64

In [14]:
df['totalcharges']=pd.to_numeric(df['totalcharges'], errors='coerce')
df['totalcharges'].dtypes

dtype('float64')

In [15]:
df['totalcharges'] = df['totalcharges'].fillna(0)

In [16]:
df.totalcharges.isnull().sum()

np.int64(0)

In [17]:
df.dtypes

customerid              str
gender                  str
seniorcitizen         int64
partner                 str
dependents              str
tenure                int64
phoneservice            str
multiplelines           str
internetservice         str
onlinesecurity          str
onlinebackup            str
deviceprotection        str
techsupport             str
streamingtv             str
streamingmovies         str
contract                str
paperlessbilling        str
paymentmethod           str
monthlycharges      float64
totalcharges        float64
churn                 int64
dtype: object

In [18]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,7033,7034,7035,7036,7037,7038,7039,7040,7041,7042
customerid,7590-vhveg,5575-gnvde,3668-qpybk,7795-cfocw,9237-hqitu,9305-cdskc,1452-kiovk,6713-okomc,7892-pookp,6388-tabgu,...,9767-fflem,0639-tsiqw,8456-qdavc,7750-eyxwz,2569-wgero,6840-resvb,2234-xaduh,4801-jzazl,8361-ltmkd,3186-ajiek
gender,female,male,male,male,female,female,male,female,female,male,...,male,female,male,female,female,male,female,female,male,male
seniorcitizen,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
partner,yes,no,no,no,no,no,no,no,yes,no,...,no,no,no,no,no,yes,yes,yes,yes,no
dependents,no,no,no,no,no,no,yes,no,no,yes,...,no,no,no,no,no,yes,yes,yes,no,no
tenure,1,34,2,45,2,8,22,10,28,62,...,38,67,19,12,72,24,72,11,4,66
phoneservice,no,yes,yes,no,yes,yes,yes,no,yes,yes,...,yes,yes,yes,no,yes,yes,yes,no,yes,yes
multiplelines,no_phone_service,no,no,no_phone_service,no,yes,yes,no_phone_service,yes,no,...,no,yes,no,no_phone_service,no,yes,yes,no_phone_service,yes,no
internetservice,dsl,dsl,dsl,dsl,fiber_optic,fiber_optic,fiber_optic,dsl,fiber_optic,dsl,...,fiber_optic,fiber_optic,fiber_optic,dsl,no,dsl,fiber_optic,dsl,fiber_optic,fiber_optic
onlinesecurity,no,yes,yes,yes,no,no,no,yes,no,yes,...,no,yes,no,no,no_internet_service,yes,no,yes,no,yes
onlinebackup,yes,no,yes,no,no,no,yes,no,no,yes,...,no,yes,no,yes,no_internet_service,no,yes,no,no,no
deviceprotection,no,yes,no,yes,no,yes,no,no,yes,no,...,no,yes,no,yes,no_internet_service,yes,yes,no,no,yes
techsupport,no,no,no,yes,no,no,no,no,yes,no,...,no,no,no,yes,no_internet_service,yes,no,no,no,yes
streamingtv,no,no,no,no,no,yes,yes,no,yes,no,...,no,yes,yes,yes,no_internet_service,yes,yes,no,no,yes
streamingmovies,no,no,no,no,no,yes,no,no,yes,no,...,no,no,no,yes,no_internet_service,yes,yes,no,no,yes
contract,month-to-month,one_year,month-to-month,one_year,month-to-month,month-to-month,month-to-month,month-to-month,month-to-month,one_year,...,month-to-month,month-to-month,month-to-month,one_year,two_year,one_year,one_year,month-to-month,month-to-month,two_year
paperlessbilling,yes,no,yes,no,yes,yes,yes,no,yes,no,...,yes,yes,yes,no,yes,yes,yes,yes,yes,yes
paymentmethod,electronic_check,mailed_check,mailed_check,bank_transfer_(automatic),electronic_check,electronic_check,credit_card_(automatic),mailed_check,electronic_check,bank_transfer_(automatic),...,credit_card_(automatic),credit_card_(automatic),bank_transfer_(automatic),electronic_check,bank_transfer_(automatic),mailed_check,credit_card_(automatic),electronic_check,mailed_check,bank_transfer_(automatic)
monthlycharges,29.85,56.95,53.85,42.3,70.7,99.65,89.1,29.75,104.8,56.15,...,69.5,102.95,78.7,60.65,21.15,84.8,103.2,29.6,74.4,105.65
totalcharges,29.85,1889.5,108.15,1840.75,151.65,820.5,1949.4,301.9,3046.05,3487.95,...,2625.25,6886.25,1495.1,743.3,1419.4,1990.5,7362.9,346.45,306.6,6844.5
churn,0,0,1,0,1,1,0,0,1,0,...,0,1,0,0,0,0,0,0,1,0

In [19]:
df.totalcharges.isnull().sum()

np.int64(0)

# 3.2 Setting Up The Validation Framework

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=1)

In [22]:
df_full_train.shape, df_test.shape

((5634, 21), (1409, 21))

In [23]:
df_full_train.head()

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
1814,5442-pptjy,male,0,yes,yes,12,yes,no,no,no_internet_service,...,no_internet_service,no_internet_service,no_internet_service,no_internet_service,two_year,no,mailed_check,19.70,258.35,0
5946,6261-rcvns,female,0,no,no,42,yes,no,dsl,yes,...,yes,yes,no,yes,one_year,no,credit_card_(automatic),73.90,3160.55,1
3881,2176-osjuv,male,0,yes,no,71,yes,yes,dsl,yes,...,no,yes,no,no,two_year,no,bank_transfer_(automatic),65.15,4681.75,0
2389,6161-erdgd,male,0,yes,yes,71,yes,yes,dsl,yes,...,yes,yes,yes,yes,one_year,no,electronic_check,85.45,6300.85,0
3676,2364-ufrom,male,0,no,no,30,yes,no,dsl,yes,...,no,yes,yes,no,one_year,no,electronic_check,70.40,2044.75,0

In [24]:
df_full_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=1)
len(df_full_train), len(df_val), len(df_test)

(4225, 1409, 1409)

In [25]:
df_train = df_full_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [26]:
y_train = df_full_train.churn.values
y_train

array([0, 0, 1, ..., 1, 0, 1], shape=(4225,))

In [27]:
len(df_full_train), len(df_val), len(df_test)

(4225, 1409, 1409)

In [28]:
y_val = df_val.churn.values
y_val

array([0, 0, 0, ..., 0, 1, 1], shape=(1409,))

In [29]:
y_test = df_test.churn.values
y_test

array([0, 0, 0, ..., 0, 0, 1], shape=(1409,))

In [30]:
del df_train['churn']
del df_val['churn']
del df_test['churn']

In [31]:
df_train.columns

Index(['customerid', 'gender', 'seniorcitizen', 'partner', 'dependents',
       'tenure', 'phoneservice', 'multiplelines', 'internetservice',
       'onlinesecurity', 'onlinebackup', 'deviceprotection', 'techsupport',
       'streamingtv', 'streamingmovies', 'contract', 'paperlessbilling',
       'paymentmethod', 'monthlycharges', 'totalcharges'],
      dtype='str')

# 3.3 EDA

In [32]:
# Check missing values
# Look at target variable (churn)
# Look at numerical and categorical variables 
df_train.isnull().sum()

customerid          0
gender              0
seniorcitizen       0
partner             0
dependents          0
tenure              0
phoneservice        0
multiplelines       0
internetservice     0
onlinesecurity      0
onlinebackup        0
deviceprotection    0
techsupport         0
streamingtv         0
streamingmovies     0
contract            0
paperlessbilling    0
paymentmethod       0
monthlycharges      0
totalcharges        0
dtype: int64

In [33]:
df_full_train = df_full_train.reset_index(drop=True)

In [34]:
df_full_train.churn.value_counts(normalize=True)
# churn rate 1    0.268639

churn
0    0.731361
1    0.268639
Name: proportion, dtype: float64

In [35]:
global_churn_rate = df_full_train.churn.mean()
round(global_churn_rate, 2)

np.float64(0.27)

In [36]:
categorical = list(df_full_train.dtypes[df_full_train.dtypes == 'str'].index)

In [37]:
categorical.remove('customerid')

In [38]:
categorical

['gender',
 'partner',
 'dependents',
 'phoneservice',
 'multiplelines',
 'internetservice',
 'onlinesecurity',
 'onlinebackup',
 'deviceprotection',
 'techsupport',
 'streamingtv',
 'streamingmovies',
 'contract',
 'paperlessbilling',
 'paymentmethod']

In [39]:
list(df_full_train.dtypes[df_full_train.dtypes == 'str'].index)

['customerid',
 'gender',
 'partner',
 'dependents',
 'phoneservice',
 'multiplelines',
 'internetservice',
 'onlinesecurity',
 'onlinebackup',
 'deviceprotection',
 'techsupport',
 'streamingtv',
 'streamingmovies',
 'contract',
 'paperlessbilling',
 'paymentmethod']

In [40]:
categorical.insert(1, 'seniorcitizen')

In [41]:
categorical

['gender',
 'seniorcitizen',
 'partner',
 'dependents',
 'phoneservice',
 'multiplelines',
 'internetservice',
 'onlinesecurity',
 'onlinebackup',
 'deviceprotection',
 'techsupport',
 'streamingtv',
 'streamingmovies',
 'contract',
 'paperlessbilling',
 'paymentmethod']

In [42]:
df_full_train[categorical].nunique()

gender              2
seniorcitizen       2
partner             2
dependents          2
phoneservice        2
multiplelines       3
internetservice     3
onlinesecurity      3
onlinebackup        3
deviceprotection    3
techsupport         3
streamingtv         3
streamingmovies     3
contract            3
paperlessbilling    2
paymentmethod       4
dtype: int64

In [43]:
numerical = ['tenure', 'monthlycharges', 'totalcharges']

In [44]:
df_full_train[numerical]

      tenure  monthlycharges  totalcharges
0         72          115.50       8425.15
1         10           95.25       1021.55
2          5           75.55        413.65
3          5           80.85        356.10
4         18           20.10        370.50
...      ...             ...           ...
4220      52           80.85       4079.55
4221      18           25.15        476.80
4222       2           90.00        190.05
4223      27           24.50        761.95
4224       9           80.85        751.65

[4225 rows x 3 columns]

# 3.4 Feature importance: Churn rate and risk ratio

In [45]:
# Identifying wich features affect our target variable
# Churn rate
# Risk ratio
# Mutual information - later

In [46]:
churn_female = df_full_train[df_full_train.gender == 'female'].churn.mean()
churn_female

np.float64(0.27666666666666667)

In [47]:
churn_male = df_full_train[df_full_train.gender == 'male'].churn.mean()
churn_male

np.float64(0.2607058823529412)

In [48]:
global_churn = df_full_train.churn.mean()
global_churn

np.float64(0.2686390532544379)

In [49]:
churn_partner = df_full_train[df_full_train.partner == 'yes'].churn.mean()
churn_partner

np.float64(0.20722057368941643)

In [50]:
churn_no_partner = df_full_train[df_full_train.partner == 'no'].churn.mean()
churn_no_partner

np.float64(0.3250113481615978)

In [51]:
global_churn - churn_partner
# global_churn - churn_partner > 0 => Less likely to churn

np.float64(0.061418479565021444)

In [52]:
global_churn - churn_no_partner
# global_churn - churn_no_partner < 0 => More likely to Churn

np.float64(-0.05637229490715995)

Risk ratio

In [53]:
churn_partner / global_churn

np.float64(0.7713717390641273)

In [54]:
churn_no_partner / global_churn

np.float64(1.209844005271146)

SELECT
    gender,
    AVG(gender),
    AVG(gender) - global_churn AS diff,
    AVG(gender) / global_churn AS risk
FROM
    data
GROUP BY
    gender;

In [55]:
df_group = df_full_train.groupby('gender').churn.agg(['mean', 'count'])
df_group['diff'] = df_group['mean'] - global_churn
df_group
df_group['risk'] = df_group['mean'] / global_churn
df_group

            mean  count      diff      risk
gender
female  0.276667   2100  0.008028  1.029883
male    0.260706   2125 -0.007933  0.970469

In [56]:
df_group2 = df_full_train.groupby('partner').churn.agg(['mean', 'count'])
df_group2['diff'] = df_group2['mean'] - global_churn
df_group2['risk'] = df_group2['mean'] / global_churn
df_group2

             mean  count      diff      risk
partner
no       0.325011   2203  0.056372  1.209844
yes      0.207221   2022 -0.061418  0.771372

In [57]:
for c in categorical:
    df_group = df_full_train.groupby('gender').churn.agg(['mean', 'count'])
df_group['diff'] = df_group['mean'] - global_churn
df_group
df_group['risk'] = df_group['mean'] / global_churn
df_group

            mean  count      diff      risk
gender
female  0.276667   2100  0.008028  1.029883
male    0.260706   2125 -0.007933  0.970469

In [58]:
from IPython.display import display

In [59]:
for c in categorical:
    df_group = df_full_train.groupby(c).churn.agg(['mean', 'count'])
    df_group['diff'] = df_group['mean'] - global_churn
    df_group
    df_group['risk'] = df_group['mean'] / global_churn
    display(df_group)
    print()
    print()

            mean  count      diff      risk
gender
female  0.276667   2100  0.008028  1.029883
male    0.260706   2125 -0.007933  0.970469

                   mean  count      diff      risk
seniorcitizen
0              0.241360   3530 -0.027279  0.898454
1              0.407194    695  0.138555  1.515767

             mean  count      diff      risk
partner
no       0.325011   2203  0.056372  1.209844
yes      0.207221   2022 -0.061418  0.771372

                mean  count      diff      risk
dependents
no          0.313579   2953  0.044940  1.167289
yes         0.164308   1272 -0.104331  0.611632

                  mean  count      diff      risk
phoneservice
no            0.256039    414 -0.012600  0.953095
yes           0.270008   3811  0.001369  1.005095

                      mean  count      diff      risk
multiplelines
no                0.252360   2013 -0.016279  0.939401
no_phone_service  0.256039    414 -0.012600  0.953095
yes               0.289766   1798  0.021127  1.078646

                     mean  count      diff      risk
internetservice
dsl              0.196676   1444 -0.071963  0.732120
fiber_optic      0.419285   1846  0.150646  1.560774
no               0.082353    935 -0.186286  0.306556

                         mean  count      diff      risk
onlinesecurity
no                   0.418816   2094  0.150177  1.559027
no_internet_service  0.082353    935 -0.186286  0.306556
yes                  0.151338   1196 -0.117301  0.563350

                         mean  count      diff      risk
onlinebackup
no                   0.395200   1875  0.126561  1.471119
no_internet_service  0.082353    935 -0.186286  0.306556
yes                  0.224028   1415 -0.044611  0.833938

                         mean  count      diff      risk
deviceprotection
no                   0.391680   1851  0.123041  1.458017
no_internet_service  0.082353    935 -0.186286  0.306556
yes                  0.231411   1439 -0.037228  0.861419

                         mean  count      diff      risk
techsupport
no                   0.415012   2065  0.146373  1.544869
no_internet_service  0.082353    935 -0.186286  0.306556
yes                  0.164082   1225 -0.104557  0.610788

                         mean  count      diff      risk
streamingtv
no                   0.345138   1666  0.076499  1.284765
no_internet_service  0.082353    935 -0.186286  0.306556
yes                  0.297414   1624  0.028775  1.107113

                         mean  count      diff      risk
streamingmovies
no                   0.337167   1652  0.068528  1.255093
no_internet_service  0.082353    935 -0.186286  0.306556
yes                  0.305861   1638  0.037222  1.138557

                    mean  count      diff      risk
contract
month-to-month  0.433102   2302  0.164463  1.612207
one_year        0.119649    911 -0.148990  0.445388
two_year        0.028656   1012 -0.239983  0.106671

                      mean  count      diff      risk
paperlessbilling
no                0.173341   1748 -0.095298  0.645256
yes               0.335890   2477  0.067251  1.250340

                               mean  count      diff      risk
paymentmethod
bank_transfer_(automatic)  0.167206    927 -0.101433  0.622419
credit_card_(automatic)    0.178611    907 -0.090028  0.664873
electronic_check           0.438075   1413  0.169436  1.630720
mailed_check               0.203476    978 -0.065163  0.757434

# 3.6 Feature Importance: Mutual Information

In [60]:
from sklearn.metrics import mutual_info_score

In [61]:
mutual_info_score(df_full_train.churn, df_full_train.contract)

0.09901566414272059

In [62]:
mutual_info_score(df_full_train.contract, df_full_train.churn)

0.09901566414272059

In [63]:
mutual_info_score(df_full_train.gender, df_full_train.churn)

0.0001620761772512247

In [64]:
mutual_info_score(df_full_train.partner, df_full_train.churn)

0.008902791538887178

In [65]:
def mutual_info_churn_score(series):
    return mutual_info_score(series, df_full_train.churn)

In [66]:
mi = df_full_train[categorical].apply(mutual_info_churn_score)
mi

gender              0.000162
seniorcitizen       0.008996
partner             0.008903
dependents          0.012709
phoneservice        0.000044
multiplelines       0.000841
internetservice     0.052373
onlinesecurity      0.061654
onlinebackup        0.042997
deviceprotection    0.041384
techsupport         0.057836
streamingtv         0.030897
streamingmovies     0.030317
contract            0.099016
paperlessbilling    0.016911
paymentmethod       0.035928
dtype: float64

In [67]:
mi.sort_values(ascending=False)

contract            0.099016
onlinesecurity      0.061654
techsupport         0.057836
internetservice     0.052373
onlinebackup        0.042997
deviceprotection    0.041384
paymentmethod       0.035928
streamingtv         0.030897
streamingmovies     0.030317
paperlessbilling    0.016911
dependents          0.012709
seniorcitizen       0.008996
partner             0.008903
multiplelines       0.000841
gender              0.000162
phoneservice        0.000044
dtype: float64

# 3.7 Feature importance: Correlation

In [97]:
# Correlation coefficient
df_full_train[numerical].corrwith(df_full_train['churn'])

tenure           -0.355962
monthlycharges    0.189665
totalcharges     -0.199645
dtype: float64

In [91]:
df_full_train[(df_full_train.tenure <= 2) ].churn.mean()

np.float64(0.6030534351145038)

In [92]:
df_full_train[(df_full_train.tenure > 2) & (df_full_train.tenure <= 12)].churn.mean()

np.float64(0.3945409429280397)

In [94]:
df_full_train[(df_full_train.tenure > 50) & (df_full_train.tenure <= 72)].churn.mean()

np.float64(0.08481421647819062)

In [95]:
df_full_train.tenure.max()

np.int64(72)